name: expense_tracker
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  uuid: ^4.2.2
  intl: any
  calendar_timeline: ^1.1.2
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.14.0
  provider: ^6.1.1
  flutter_slidable: ^3.0.1
  firebase_core: ^2.24.2
  shared_preferences: ^2.2.2
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
  generate: true

  assets:
     - assets/images/
     - assets/icons/

  fonts:
     - family: Lato
       fonts:
         - asset: assets/fonts/Lato-Light.ttf
         - asset: assets/fonts/Lato-Regular.ttf
         - asset: assets/fonts/Lato-Bold.ttf

     - family: Rubik
       fonts:
         - asset: assets/fonts/rubik/Rubik-Light.ttf
         - asset: assets/fonts/rubik/Rubik-Regular.ttf
         - asset: assets/fonts/rubik/Rubik-Medium.ttf
         - asset: assets/fonts/rubik/Rubik-SemiBold.ttf
         - asset: assets/fonts/rubik/Rubik-Bold.ttf

#     - family: Trajan Pro
#       fonts:
#         - asset: fonts/TrajanPro.ttf
#         - asset: fonts/TrajanPro_Bold.ttf
#           weight: 700